export default {
  title: 'Ads',
  eventTypes: [
    {
      event: 'Global',
      attributes: [
        ['appName', 'Platform'],
        ['playerVersion', 'Player'],
        ['playerName', 'Player'],
        ['contentSrc', 'Content'],
        ['countryCode', 'Geography'],
        ['contentIsLive', 'Content'],
        ['contentTitle', 'Content'],
      ],
    },
    {
      event: 'PageAction',
      eventSelector: { attribute: 'Delivery Type', value: 'Web' },
      attributes: [
        ['adPartner', 'Ad'],
        ['adPosition', 'Ad'],
        ['adTitle', 'Ad'],
        ['adPartner', 'Ad'],
        ['adSrc', 'Ad'],
        ['adBreakId', 'Ad'],
        ['adCreativeId', 'Ad'],  
        ['userAgentName', 'Platform'],
        ['userAgentName', 'Platform'],
        ['userAgentOS', 'Platform'],
        ['userAgentVersion', 'Platform'],
        ['asnOrganization', 'Geography'],
        ['city', 'Geography'],
        ['regionCode', 'Geography'],
        ['message', 'Error'],
      ],
    },
    {
      event: 'MobileVideo',
      eventSelector: { attribute: 'Delivery Type', value: 'Mobile' },
      attributes: [
        ['isAd', 'Content'],
        ['asnOrganization', 'Geography'],
        ['city', 'Geography'],
        ['regionCode', 'Geography'],
        ['device', 'Platform'],
        ['deviceGroup', 'Platform'],
        ['deviceType', 'Platform'],
        ['osName', 'Platform'],
        ['osVersion', 'Platform'],
        ['appVersion', 'Platform'],
        ['message', 'Error'],
      ],
    },
    {
      event: 'RokuVideo',
      eventSelector: { attribute: 'Delivery Type', value: 'OTT' },
      attributes: [
        ['device', 'Platform'],
        ['deviceGroup', 'Platform'],
        ['deviceType', 'Platform'],
        ['osName', 'Platform'],
        ['osVersion', 'Platform'],
        ['errorMessage', 'Error'],
      ],
    },
  ],
  metrics: [
    {
      id: 'AS',
      title: 'Ads Shown',
      query: {
        nrql: `SELECT count(*) as 'result' from PageAction, MobileVideo where actionName = 'AD_START'`,
        lookup: 'result',
      },
      detailDashboardId: 'AS-Detail',
    },
    {
      id: 'ACR',
      title: 'Ad Click Ratio',
      query: {
        nrql: `SELECT filter(count(*), WHERE actionName = 'AD_CLICK') / filter(count(*), WHERE actionName = 'AD_START') * 100  as 'result' from PageAction, MobileVideo `,
        lookup: 'result',
      },
      detailDashboardId: 'ACR-Detail',
    },
    {
      id: 'AER',
      title: 'Ad Error Ratio',
      query: {
        nrql: `SELECT filter(count(*), WHERE actionName = 'AD_ERROR') / filter(count(*), WHERE actionName = 'AD_START') * 100  as 'result' from PageAction, MobileVideo `,
        lookup: 'result',
      },
      detailDashboardId: 'AER-Detail',
    },
    {
      id: 'AIR',
      title: 'Ad Interruption Ratio',
      query: {
        nrql: `SELECT filter(count(*), WHERE actionName = 'AD_BREAK_START') / filter(count(*), WHERE actionName = 'AD_START') * 100  as 'result' from PageAction, MobileVideo `,
        lookup: 'result',
      },
      detailDashboardId: 'AIR-Detail',
    },
    {
      id: 'AJT',
      title: 'Join Time for Ads (s)',
      query: {
        nrql: `SELECT percentile(timeSinceAdRequested/1000, 50) as 'percentile' FROM PageAction, MobileVideo WHERE actionName in ('AD_START','AD_BREAK_START')`,
        lookup: 'percentile',
      },
      detailDashboardId: 'AJT-Detail',
    },
  ],
  detailDashboards: [
    {
      id: 'AS-Detail',
      config: [
        {
          nrql: `SELECT count(*) as 'Ads' from PageAction, MobileVideo where actionName = 'AD_START' `,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Ads Shown',
          useSince: true,
        },
        {
          nrql: `SELECT count(*) as 'Ads' FROM PageAction, MobileVideo where actionName = 'AD_START' FACET viewId LIMIT 25`,
          noFacet: true,
          columnStart: 5,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'bar',
          title: 'Views with most Ads Shown (Click for details)',
          useSince: true,
          click: 'openSession',
        },
        {
          nrql: `SELECT funnel(viewId, WHERE actionName='AD_REQUEST' as 'Ad Requested', WHERE actionName='AD_START' as 'Ad Started', WHERE actionName='AD_QUARTILE' and adQuartile = 1 as 'First Quartile', WHERE actionName='AD_QUARTILE' and adQuartile = 2 as 'Second Quartile', WHERE actionName='AD_QUARTILE' and adQuartile = 3 as 'Third Quartile', WHERE actionName='AD_END' as 'Ad Completed', WHERE actionName='AD_CLICK' as 'Ad Click') FROM PageAction, MobileVideo `,
          noFacet: true,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'medium',
          chartType: 'funnel',
          title: 'Ad Funnel',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo SELECT count(*) WHERE actionName='AD_START' TIMESERIES `,
          columnStart: 5,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'line',
          title: 'Ads Shown Trend',
          useSince: true,
        },
      ],
    },
    {
      id: 'ACR-Detail',
      config: [
        {
          nrql: `SELECT filter(count(*), WHERE actionName = 'AD_CLICK') / filter(count(*), WHERE actionName = 'AD_START') * 100  as 'result' from PageAction, MobileVideo `,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Ads Click ratio',
          useSince: true,
        },
        {
          nrql: `SELECT count(*) as 'Ads' FROM PageAction, MobileVideo where actionName = 'AD_CLICK' FACET viewId LIMIT 25`,
          noFacet: true,
          columnStart: 5,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'bar',
          title: 'Views with most Ads Clicks (Click for details)',
          useSince: true,
          click: 'openSession',
        },
        {
          nrql: `SELECT funnel(viewId, WHERE actionName='AD_REQUEST' as 'Ad Requested', WHERE actionName='AD_START' as 'Ad Started', WHERE actionName='AD_QUARTILE' and adQuartile = 1 as 'First Quartile', WHERE actionName='AD_QUARTILE' and adQuartile = 2 as 'Second Quartile', WHERE actionName='AD_QUARTILE' and adQuartile = 3 as 'Third Quartile', WHERE actionName='AD_END' as 'Ad Completed', WHERE actionName='AD_CLICK' as 'Ad Click') FROM PageAction, MobileVideo `,
          noFacet: true,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'medium',
          chartType: 'funnel',
          title: 'Ad Funnel',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo SELECT count(*) WHERE actionName = 'AD_CLICK' TIMESERIES `,
          columnStart: 5,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'line',
          title: 'Ads Click Trend',
          useSince: true,
        },
      ],
    },
    {
      id: 'AER-Detail',
      config: [
        {
          nrql: `SELECT count(*) as 'Ads' FROM PageAction, MobileVideo where actionName = 'AD_ERROR' AND userAuthStatus = 'logged in' FACET viewId LIMIT 25`,
          noFacet: true,
          columnStart: 1,
          columnEnd: 6,
          chartSize: 'small',
          chartType: 'bar',
          title: 'Views with most Ads Errors as active user (Click for details)',
          useSince: true,
          click: 'openSession',
        },
        {
          nrql: `SELECT count(*) as 'Ads' FROM PageAction, MobileVideo where actionName = 'AD_ERROR' AND userAuthStatus != 'logged in' FACET viewId LIMIT 25`,
          noFacet: true,
          columnStart: 7,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'bar',
          title: 'Views with most Ads Errors as anonymous user(Click for details)',
          useSince: true,
          click: 'openSession',
        },
        {
          nrql: `FROM PageAction, MobileVideo SELECT count(*) where actionName = 'AD_ERROR' AND userAuthStatus = 'logged in' TIMESERIES `,
          columnStart: 1,
          columnEnd: 6,
          chartSize: 'small',
          chartType: 'line',
          title: 'Ads Errors as active user',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo SELECT count(*) where actionName = 'AD_ERROR' AND userAuthStatus != 'logged in' TIMESERIES `,
          columnStart: 7,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'line',
          title: 'Ads Errors as anonymous user',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo SELECT count(*) where actionName = 'AD_ERROR' AND userAuthStatus = 'logged in' facet userAisuid, deviceType, appName, adId, adBreakId, appVersion, osVersion, errorMessage`,
          noFacet: true,
          columnStart: 1,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'table',
          title: 'Aisuid with Ads Errors as active user',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo SELECT count(*) where actionName = 'AD_ERROR' AND userAuthStatus != 'logged in' facet deviceUuid, deviceType, appName, adId, adBreakId, appVersion, osVersion, errorMessage`,
          noFacet: true,
          columnStart: 1,
          columnEnd: 12,
          chartSize: 'medium',
          chartType: 'table',
          title: 'deviceUuid with Ads Errors as anonymous user',
          useSince: true,
        },
      ],
    },
    {
      id: 'AIR-Detail',
      config: [
        {
          nrql: `SELECT filter(count(*), WHERE actionName = 'AD_BREAK_START') / filter(count(*), WHERE actionName = 'AD_START') * 100  as 'result' from PageAction, MobileVideo `,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Ad Interruption Ratio',
          useSince: true,
        },
        {
          nrql: `SELECT count(*) as 'Ads' FROM PageAction, MobileVideo where actionName = 'AD_BREAK_START' FACET viewId LIMIT 25`,
          noFacet: true,
          columnStart: 5,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'bar',
          title: 'Views with most Ads Interruption (Click for details)',
          useSince: true,
          click: 'openSession',
        },
        {
          nrql: `SELECT funnel(viewId, WHERE actionName='AD_REQUEST' as 'Ad Requested', WHERE actionName='AD_START' as 'Ad Started', WHERE actionName='AD_QUARTILE' and adQuartile = 1 as 'First Quartile', WHERE actionName='AD_QUARTILE' and adQuartile = 2 as 'Second Quartile', WHERE actionName='AD_QUARTILE' and adQuartile = 3 as 'Third Quartile', WHERE actionName='AD_END' as 'Ad Completed', WHERE actionName='AD_CLICK' as 'Ad Click') FROM PageAction, MobileVideo `,
          noFacet: true,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'medium',
          chartType: 'funnel',
          title: 'Ad Funnel',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo SELECT count(*) WHERE actionName = 'AD_BREAK_START' TIMESERIES `,
          columnStart: 5,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'line',
          title: 'Ads Break Trend',
          useSince: true,
        },
      ],
    },
    {
      id: 'ASFR-Detail',
      config: [
        {
          nrql: `SELECT filter(count(*), WHERE actionName = 'AD_ERROR' and adPlayhead < 2000) / filter(count(*), WHERE actionName = 'AD_REQUEST') * 100 as 'result' from PageAction, MobileVideo `,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Ad Start Failure Ratio',
          useSince: true,
        },
        {
          nrql: `SELECT count(*) as 'Ads' FROM PageAction, MobileVideo WHERE actionName = 'AD_ERROR' and adPlayhead < 2000 FACET viewId LIMIT 25`,
          noFacet: true,
          columnStart: 5,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'bar',
          title: 'Views with Ad Start Failure (Click for details)',
          useSince: true,
          click: 'openSession',
        },
        {
          nrql: `SELECT funnel(viewId, WHERE actionName='AD_REQUEST' as 'Ad Requested', WHERE actionName='AD_START' as 'Ad Started', WHERE actionName='AD_QUARTILE' and adQuartile = 1 as 'First Quartile', WHERE actionName='AD_QUARTILE' and adQuartile = 2 as 'Second Quartile', WHERE actionName='AD_QUARTILE' and adQuartile = 3 as 'Third Quartile', WHERE actionName='AD_END' as 'Ad Completed', WHERE actionName='AD_CLICK' as 'Ad Click') FROM PageAction, MobileVideo `,
          noFacet: true,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'medium',
          chartType: 'funnel',
          title: 'Ad Funnel',
          useSince: true,
        },
      ],
    },
    {
      id: 'AJT-Detail',
      config: [
        {
          nrql: `SELECT percentile(timeSinceAdRequested/1000, 50) as 'percentile' FROM PageAction, MobileVideo WHERE actionName in ('AD_START','AD_BREAK_START')`,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'small',
          chartType: 'billboard',
          title: 'Join Time',
          useSince: true,
        },
        {
          nrql: `SELECT average(timeSinceAdRequested) as 'Ads' FROM PageAction, MobileVideo where actionName = 'AD_BREAK_START' FACET viewId LIMIT 25`,
          noFacet: true,
          columnStart: 5,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'bar',
          title: 'Views with most Ads Break (Click for details)',
          useSince: true,
          click: 'openSession',
        },
        {
          nrql: `SELECT funnel(viewId, WHERE actionName='AD_REQUEST' as 'Ad Requested', WHERE actionName='AD_START' as 'Ad Started', WHERE actionName='AD_QUARTILE' and adQuartile = 1 as 'First Quartile', WHERE actionName='AD_QUARTILE' and adQuartile = 2 as 'Second Quartile', WHERE actionName='AD_QUARTILE' and adQuartile = 3 as 'Third Quartile', WHERE actionName='AD_END' as 'Ad Completed', WHERE actionName='AD_CLICK' as 'Ad Click') FROM PageAction, MobileVideo `,
          noFacet: true,
          columnStart: 1,
          columnEnd: 4,
          chartSize: 'medium',
          chartType: 'funnel',
          title: 'Ad Funnel',
          useSince: true,
        },
        {
          nrql: `FROM PageAction, MobileVideo SELECT average(adPlayhead) WHERE actionName in ('AD_START','AD_BREAK_START') TIMESERIES `,
          facets: 'actionName',
          columnStart: 5,
          columnEnd: 12,
          chartSize: 'small',
          chartType: 'line',
          title: 'Ads Playhead Trend',
          useSince: true,
        },
      ],
    },
  ],
}
